--- #YAML:1.0
name: Lufs
version: 0.21
author:
  - Raoul Zwart <rlzwart@cpan.org>
abstract: Perl plug for lufs
license: perl
requires:
  HTML::TokeParser::Simple: 0
  Inline::MakeMaker: 0
  Linux::Pid: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Lufs:
    file: lib/Lufs.pm
    version: 0.21
  Lufs::C:
    file: lib/Lufs/C.pm
  Lufs::Glue:
    file: lib/Lufs/Glue.pm
  Lufs::Http:
    file: lib/Lufs/Http.pm
  Lufs::Local:
    file: lib/Lufs/Local.pm
  Lufs::Mux:
    file: lib/Lufs/Mux.pm
  Lufs::NetHood:
    file: lib/Lufs/NetHood.pm
  Lufs::Ram:
    file: lib/Lufs/Ram.pm
  Lufs::Ram::Node:
    file: lib/Lufs/Ram.pm
  Lufs::Rot13:
    file: lib/Lufs/Rot13.pm
  Lufs::Sql:
    file: lib/Lufs/Sql.pm
  Lufs::Sql::DBI::Node:
    file: lib/Lufs/Sql.pm
  Lufs::Stub:
    file: lib/Lufs/Stub.pm
  Lufs::Svn:
    file: lib/Lufs/Svn.pm
  Lufs::Svn::Svn:
    file: lib/Lufs/Svn.pm
  Lufs::Svn::Svn::System:
    file: lib/Lufs/Svn.pm
generated_by: Module::Build version 0.22
